### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by aluchkovsky** [tekmaven/NServiceBus.Persistence.MongoDb#15]
Could you please create and upload to nuget.org an updated nuget package based on this 2nd latest commit https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/commit/59b305b79f3a7782ca9412bac8dcf7d2f2004f3c to get a fix for issue #8 (using nsb 5.2.14) Thank you!

**Comment by tekmaven** [comment]
This is released as a part of NServiceBus.Persistence.MongoDb 8.0.24.
